Update export-director-metadata

diff --git a/scripts/export-director-metadata b/scripts/export-director-metadata
--- a/scripts/export-director-metadata
+++ b/scripts/export-director-metadata
@@ -53,7 +53,7 @@ if [ ! -z ${OPSMAN_PRIVATE_KEY:+x} ]; then
   
   ssh -4 -D 5000 -NC "ubuntu@${opsman_host}" -i "${opsman_private_key_path}" -o ServerAliveInterval=60 -o StrictHostKeyChecking=no &
   ssh_socks_proxy_pid="$!"
-  trap cleanup_socks_proxy EXIT
+  # trap cleanup_socks_proxy EXIT
   export BOSH_ALL_PROXY=socks5://localhost:5000
   echo "Using BOSH_ALL_PROXY"
 fi
